### ISSUE TITLE
Missing template parameter in `inclusive_scan` description

### ISSUE THREAD

**Issue by timsong-cpp** [cplusplus/parallelism-ts#49]
[parallel.alg.inclusive.scan]/3 depicts

```
template< class InputIterator, class OutputIterator, class BinaryOperation> 
OutputIterator inclusive_scan(InputIterator first, InputIterator last,
                              OutputIterator result,
                              BinaryOperation binary_op, T init);
```

This is missing a template parameter `T` (i.e., should presumably be `template< class InputIterator, class OutputIterator, class BinaryOperation, class T>`). The synopsis looks correct.

**Comment by jaredhoberock** [comment]
Thanks for catching this, it's fixed in the source.
