### ISSUE TITLE
incorrect return type of static_simd_cast

### ISSUE THREAD

**Issue by mattkretz** [cplusplus/parallelism-ts#65]
[parallel.simd.casts] p12 specifies the return type to be "`simd<T, Abi>` if either `U` is `T` or `U` and `T` are integral types that only differ in signedness". This rule is inconsistent wrt. `char` / `signed char` / `unsigned char` and `wchar_t`, `char16_t`, and `char32_t`. E.g. `static_simd_cast<char>(simd<signed char>())` produces a `fixed_size` ABI, instead of the `compatible` ABI as is the case for `static_simd_cast<unsigned char>(simd<signed char>())`.

Proposed resolution:

Modify 9.4.5/12
-  `T` if `is_simd_v<T>` is true, otherwise
- `simd<T, Abi>` if either `U` is `T` or <del>`U` and `T` are integral types that only differ in signedness</del><ins>`make_signed_t<U>` is `make_signed_t<T>`</ins>, otherwise
- `simd<T, simd_abi::fixed_size<simd<U, Abi>::size()>>`.

**Comment by mattkretz** [comment]
According to [meta.trans.sign], `make_signed_t` alone does not suffice. `make_signed_t<wchar_t>` can be `wchar_t` if `is_signed_v<wchar_t>` is true. New proposed resolution:

Modify 9.4.5/12
-  `T` if `is_simd_v<T>` is true, otherwise
- `simd<T, Abi>` if either `U` is `T` or <del>`U` and `T` are integral types that only differ in signedness</del><ins>`make_signed_t<make_unsigned_t<U>>` is `make_signed_t<make_unsigned<T>>`</ins>, otherwise
- `simd<T, simd_abi::fixed_size<simd<U, Abi>::size()>>`.

**Comment by brycelelbach** [comment]
P1111r0 should deal with this. It was reported in an NB comment on the Parallelism TS v2 (CH15).

**Comment by mattkretz** [comment]
this is resolved after NB comments were applied
